add_test( [==[AlternatingIterator tests]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[AlternatingIterator tests]==]  )
set_tests_properties( [==[AlternatingIterator tests]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[SetBitIterator tests]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[SetBitIterator tests]==]  )
set_tests_properties( [==[SetBitIterator tests]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( EnumOverOptimisation_BoundsCheck /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js EnumOverOptimisation_BoundsCheck  )
set_tests_properties( EnumOverOptimisation_BoundsCheck PROPERTIES WORKING_DIRECTORY /src/build)
add_test( EnumOverOptimisation_Bitmask /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js EnumOverOptimisation_Bitmask  )
set_tests_properties( EnumOverOptimisation_Bitmask PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[FlatSet - basic]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[FlatSet - basic]==]  )
set_tests_properties( [==[FlatSet - basic]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[History Rotation and Reporting tests]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[History Rotation and Reporting tests]==]  )
set_tests_properties( [==[History Rotation and Reporting tests]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelSlopeAdditionTest - A one corner slope, plus the opposite three corner slope results in a flat but elevated slope]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelSlopeAdditionTest - A one corner slope\, plus the opposite three corner slope results in a flat but elevated slope]==]  )
set_tests_properties( [==[PartialPixelSlopeAdditionTest - A one corner slope, plus the opposite three corner slope results in a flat but elevated slope]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelSlopeAdditionTest - Diagonal slopes with their opposite slope result in a flat but elevated slope]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelSlopeAdditionTest - Diagonal slopes with their opposite slope result in a flat but elevated slope]==]  )
set_tests_properties( [==[PartialPixelSlopeAdditionTest - Diagonal slopes with their opposite slope result in a flat but elevated slope]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelSlopeAdditionTest - Half tile slopes with their opposite half tile slope result in a flat but elevated slope]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelSlopeAdditionTest - Half tile slopes with their opposite half tile slope result in a flat but elevated slope]==]  )
set_tests_properties( [==[PartialPixelSlopeAdditionTest - Half tile slopes with their opposite half tile slope result in a flat but elevated slope]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelSlopeAdditionTest - Two opposite one corner slopes result in the two corner slope with opposite corners]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelSlopeAdditionTest - Two opposite one corner slopes result in the two corner slope with opposite corners]==]  )
set_tests_properties( [==[PartialPixelSlopeAdditionTest - Two opposite one corner slopes result in the two corner slope with opposite corners]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelSlopeAdditionTest - A steep slope is a one corner slope on top of a three corner slope]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelSlopeAdditionTest - A steep slope is a one corner slope on top of a three corner slope]==]  )
set_tests_properties( [==[PartialPixelSlopeAdditionTest - A steep slope is a one corner slope on top of a three corner slope]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelSlopeAdditionTest - A half tile steep slope is a one corner half tile on top of a three corner slope]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelSlopeAdditionTest - A half tile steep slope is a one corner half tile on top of a three corner slope]==]  )
set_tests_properties( [==[PartialPixelSlopeAdditionTest - A half tile steep slope is a one corner half tile on top of a three corner slope]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - One corner up slopes - SLOPE_N]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - One corner up slopes - SLOPE_N]==]  )
set_tests_properties( [==[PartialPixelTest - One corner up slopes - SLOPE_N]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - One corner up slopes - SLOPE_E]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - One corner up slopes - SLOPE_E]==]  )
set_tests_properties( [==[PartialPixelTest - One corner up slopes - SLOPE_E]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - One corner up slopes - SLOPE_S]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - One corner up slopes - SLOPE_S]==]  )
set_tests_properties( [==[PartialPixelTest - One corner up slopes - SLOPE_S]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - One corner up slopes - SLOPE_W]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - One corner up slopes - SLOPE_W]==]  )
set_tests_properties( [==[PartialPixelTest - One corner up slopes - SLOPE_W]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_NE]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Two corner up\, diagonal slopes - SLOPE_NE]==]  )
set_tests_properties( [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_NE]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_SE]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Two corner up\, diagonal slopes - SLOPE_SE]==]  )
set_tests_properties( [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_SE]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_SW]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Two corner up\, diagonal slopes - SLOPE_SW]==]  )
set_tests_properties( [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_SW]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_NW]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Two corner up\, diagonal slopes - SLOPE_NW]==]  )
set_tests_properties( [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_NW]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Two opposite corner up slopes - SLOPE_NS]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Two opposite corner up slopes - SLOPE_NS]==]  )
set_tests_properties( [==[PartialPixelTest - Two opposite corner up slopes - SLOPE_NS]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Two opposite corner up slopes - SLOPE_EW]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Two opposite corner up slopes - SLOPE_EW]==]  )
set_tests_properties( [==[PartialPixelTest - Two opposite corner up slopes - SLOPE_EW]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Three corner up slopes - SLOPE_ENW]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Three corner up slopes - SLOPE_ENW]==]  )
set_tests_properties( [==[PartialPixelTest - Three corner up slopes - SLOPE_ENW]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Three corner up slopes - SLOPE_SEN]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Three corner up slopes - SLOPE_SEN]==]  )
set_tests_properties( [==[PartialPixelTest - Three corner up slopes - SLOPE_SEN]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Three corner up slopes - SLOPE_WSE]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Three corner up slopes - SLOPE_WSE]==]  )
set_tests_properties( [==[PartialPixelTest - Three corner up slopes - SLOPE_WSE]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Three corner up slopes - SLOPE_NWS]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Three corner up slopes - SLOPE_NWS]==]  )
set_tests_properties( [==[PartialPixelTest - Three corner up slopes - SLOPE_NWS]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_N]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_N]==]  )
set_tests_properties( [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_N]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_E]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_E]==]  )
set_tests_properties( [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_E]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_S]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_S]==]  )
set_tests_properties( [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_S]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_W]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_W]==]  )
set_tests_properties( [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_W]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_N]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_N]==]  )
set_tests_properties( [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_N]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_E]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_E]==]  )
set_tests_properties( [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_E]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_S]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_S]==]  )
set_tests_properties( [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_S]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_W]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_W]==]  )
set_tests_properties( [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_W]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_N]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_N]==]  )
set_tests_properties( [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_N]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_E]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_E]==]  )
set_tests_properties( [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_E]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_S]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_S]==]  )
set_tests_properties( [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_S]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_W]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_W]==]  )
set_tests_properties( [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_W]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[DivideApproxTest - Negative]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[DivideApproxTest - Negative]==]  )
set_tests_properties( [==[DivideApproxTest - Negative]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[DivideApproxTest, Divide]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[DivideApproxTest\, Divide]==]  )
set_tests_properties( [==[DivideApproxTest, Divide]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[IntSqrtTest - Zero]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[IntSqrtTest - Zero]==]  )
set_tests_properties( [==[IntSqrtTest - Zero]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[IntSqrtTest - FindSqRt]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[IntSqrtTest - FindSqRt]==]  )
set_tests_properties( [==[IntSqrtTest - FindSqRt]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( ClampTo /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js ClampTo  )
set_tests_properties( ClampTo PROPERTIES WORKING_DIRECTORY /src/build)
add_test( SoftClamp /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js SoftClamp  )
set_tests_properties( SoftClamp PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StringBuilder - basic]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StringBuilder - basic]==]  )
set_tests_properties( [==[StringBuilder - basic]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StringBuilder - binary]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StringBuilder - binary]==]  )
set_tests_properties( [==[StringBuilder - binary]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StringBuilder - text]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StringBuilder - text]==]  )
set_tests_properties( [==[StringBuilder - text]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StringConsumer - basic]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StringConsumer - basic]==]  )
set_tests_properties( [==[StringConsumer - basic]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StringConsumer - binary8]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StringConsumer - binary8]==]  )
set_tests_properties( [==[StringConsumer - binary8]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StringConsumer - binary16]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StringConsumer - binary16]==]  )
set_tests_properties( [==[StringConsumer - binary16]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StringConsumer - binary32]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StringConsumer - binary32]==]  )
set_tests_properties( [==[StringConsumer - binary32]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StringConsumer - binary64]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StringConsumer - binary64]==]  )
set_tests_properties( [==[StringConsumer - binary64]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StringConsumer - utf8]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StringConsumer - utf8]==]  )
set_tests_properties( [==[StringConsumer - utf8]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StringConsumer - conditions]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StringConsumer - conditions]==]  )
set_tests_properties( [==[StringConsumer - conditions]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StringConsumer - ascii]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StringConsumer - ascii]==]  )
set_tests_properties( [==[StringConsumer - ascii]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StringConsumer - parse int]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StringConsumer - parse int]==]  )
set_tests_properties( [==[StringConsumer - parse int]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StringConsumer - invalid int]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StringConsumer - invalid int]==]  )
set_tests_properties( [==[StringConsumer - invalid int]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StringConsumer - most negative]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StringConsumer - most negative]==]  )
set_tests_properties( [==[StringConsumer - most negative]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( InPlaceReplacement /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js InPlaceReplacement  )
set_tests_properties( InPlaceReplacement PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StrCompareIgnoreCase - std::string]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StrCompareIgnoreCase - std::string]==]  )
set_tests_properties( [==[StrCompareIgnoreCase - std::string]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StrCompareIgnoreCase - std::string_view]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StrCompareIgnoreCase - std::string_view]==]  )
set_tests_properties( [==[StrCompareIgnoreCase - std::string_view]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StrEqualsIgnoreCase - std::string]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StrEqualsIgnoreCase - std::string]==]  )
set_tests_properties( [==[StrEqualsIgnoreCase - std::string]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StrEqualsIgnoreCase - std::string_view]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StrEqualsIgnoreCase - std::string_view]==]  )
set_tests_properties( [==[StrEqualsIgnoreCase - std::string_view]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StrStartsWithIgnoreCase - std::string]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StrStartsWithIgnoreCase - std::string]==]  )
set_tests_properties( [==[StrStartsWithIgnoreCase - std::string]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StrStartsWithIgnoreCase - std::string_view]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StrStartsWithIgnoreCase - std::string_view]==]  )
set_tests_properties( [==[StrStartsWithIgnoreCase - std::string_view]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StrEndsWithIgnoreCase - std::string]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StrEndsWithIgnoreCase - std::string]==]  )
set_tests_properties( [==[StrEndsWithIgnoreCase - std::string]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[StrEndsWithIgnoreCase - std::string_view]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[StrEndsWithIgnoreCase - std::string_view]==]  )
set_tests_properties( [==[StrEndsWithIgnoreCase - std::string_view]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( FormatArrayAsHex /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js FormatArrayAsHex  )
set_tests_properties( FormatArrayAsHex PROPERTIES WORKING_DIRECTORY /src/build)
add_test( ConvertHexToBytes /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js ConvertHexToBytes  )
set_tests_properties( ConvertHexToBytes PROPERTIES WORKING_DIRECTORY /src/build)
add_test( StrTrimInPlace /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js StrTrimInPlace  )
set_tests_properties( StrTrimInPlace PROPERTIES WORKING_DIRECTORY /src/build)
add_test( StrTrimView /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js StrTrimView  )
set_tests_properties( StrTrimView PROPERTIES WORKING_DIRECTORY /src/build)
add_test( FixSCCEncoded /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js FixSCCEncoded  )
set_tests_properties( FixSCCEncoded PROPERTIES WORKING_DIRECTORY /src/build)
add_test( FixSCCEncodedNegative /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js FixSCCEncodedNegative  )
set_tests_properties( FixSCCEncodedNegative PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[EncodedString::ReplaceParam - positive]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[EncodedString::ReplaceParam - positive]==]  )
set_tests_properties( [==[EncodedString::ReplaceParam - positive]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[EncodedString::ReplaceParam - negative]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[EncodedString::ReplaceParam - negative]==]  )
set_tests_properties( [==[EncodedString::ReplaceParam - negative]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( Authentication_KeyExchangeOnly /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js Authentication_KeyExchangeOnly  )
set_tests_properties( Authentication_KeyExchangeOnly PROPERTIES WORKING_DIRECTORY /src/build)
add_test( Authentication_PAKE /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js Authentication_PAKE  )
set_tests_properties( Authentication_PAKE PROPERTIES WORKING_DIRECTORY /src/build)
add_test( Authentication_AuthorizedKey /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js Authentication_AuthorizedKey  )
set_tests_properties( Authentication_AuthorizedKey PROPERTIES WORKING_DIRECTORY /src/build)
add_test( Authentication_Combined /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js Authentication_Combined  )
set_tests_properties( Authentication_Combined PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[Encryption handling]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[Encryption handling]==]  )
set_tests_properties( [==[Encryption handling]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[Squirrel -> JSON conversion]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[Squirrel -> JSON conversion]==]  )
set_tests_properties( [==[Squirrel -> JSON conversion]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[JSON -> Squirrel conversion]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[JSON -> Squirrel conversion]==]  )
set_tests_properties( [==[JSON -> Squirrel conversion]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[WindowDesc - ini_key uniqueness]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[WindowDesc - ini_key uniqueness]==]  )
set_tests_properties( [==[WindowDesc - ini_key uniqueness]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[WindowDesc - ini_key validity]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[WindowDesc - ini_key validity]==]  )
set_tests_properties( [==[WindowDesc - ini_key validity]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[WindowDesc - NWidgetParts properly closed]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[WindowDesc - NWidgetParts properly closed]==]  )
set_tests_properties( [==[WindowDesc - NWidgetParts properly closed]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[WindowDesc - NWidgetPart validity]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[WindowDesc - NWidgetPart validity]==]  )
set_tests_properties( [==[WindowDesc - NWidgetPart validity]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[SpiralTileSequence - minimum]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[SpiralTileSequence - minimum]==]  )
set_tests_properties( [==[SpiralTileSequence - minimum]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[SpiralTileSequence - odd]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[SpiralTileSequence - odd]==]  )
set_tests_properties( [==[SpiralTileSequence - odd]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[SpiralTileSequence - even]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[SpiralTileSequence - even]==]  )
set_tests_properties( [==[SpiralTileSequence - even]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[SpiralTileSequence - zero hole]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[SpiralTileSequence - zero hole]==]  )
set_tests_properties( [==[SpiralTileSequence - zero hole]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[SpiralTileSequence - normal hole]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[SpiralTileSequence - normal hole]==]  )
set_tests_properties( [==[SpiralTileSequence - normal hole]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[Utf8View - empty]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[Utf8View - empty]==]  )
set_tests_properties( [==[Utf8View - empty]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[Utf8View - invalid]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[Utf8View - invalid]==]  )
set_tests_properties( [==[Utf8View - invalid]==] PROPERTIES WORKING_DIRECTORY /src/build)
add_test( [==[Utf8View - iterate]==] /emsdk/node/16.20.0_64bit/bin/node /src/build/openttd_test.js [==[Utf8View - iterate]==]  )
set_tests_properties( [==[Utf8View - iterate]==] PROPERTIES WORKING_DIRECTORY /src/build)
set( openttd_test_TESTS [==[AlternatingIterator tests]==] [==[SetBitIterator tests]==] EnumOverOptimisation_BoundsCheck EnumOverOptimisation_Bitmask [==[FlatSet - basic]==] [==[History Rotation and Reporting tests]==] [==[PartialPixelSlopeAdditionTest - A one corner slope, plus the opposite three corner slope results in a flat but elevated slope]==] [==[PartialPixelSlopeAdditionTest - Diagonal slopes with their opposite slope result in a flat but elevated slope]==] [==[PartialPixelSlopeAdditionTest - Half tile slopes with their opposite half tile slope result in a flat but elevated slope]==] [==[PartialPixelSlopeAdditionTest - Two opposite one corner slopes result in the two corner slope with opposite corners]==] [==[PartialPixelSlopeAdditionTest - A steep slope is a one corner slope on top of a three corner slope]==] [==[PartialPixelSlopeAdditionTest - A half tile steep slope is a one corner half tile on top of a three corner slope]==] [==[PartialPixelTest - One corner up slopes - SLOPE_N]==] [==[PartialPixelTest - One corner up slopes - SLOPE_E]==] [==[PartialPixelTest - One corner up slopes - SLOPE_S]==] [==[PartialPixelTest - One corner up slopes - SLOPE_W]==] [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_NE]==] [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_SE]==] [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_SW]==] [==[PartialPixelTest - Two corner up, diagonal slopes - SLOPE_NW]==] [==[PartialPixelTest - Two opposite corner up slopes - SLOPE_NS]==] [==[PartialPixelTest - Two opposite corner up slopes - SLOPE_EW]==] [==[PartialPixelTest - Three corner up slopes - SLOPE_ENW]==] [==[PartialPixelTest - Three corner up slopes - SLOPE_SEN]==] [==[PartialPixelTest - Three corner up slopes - SLOPE_WSE]==] [==[PartialPixelTest - Three corner up slopes - SLOPE_NWS]==] [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_N]==] [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_E]==] [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_S]==] [==[PartialPixelTest - Normal half tile slopes - SLOPE/CORNER_W]==] [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_N]==] [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_E]==] [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_S]==] [==[PartialPixelTest - Steep slopes - SLOPE_STEEP_W]==] [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_N]==] [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_E]==] [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_S]==] [==[PartialPixelTest - Half tile on top of steep slopes - SLOPE_STEEP/CORNER_W]==] [==[DivideApproxTest - Negative]==] [==[DivideApproxTest, Divide]==] [==[IntSqrtTest - Zero]==] [==[IntSqrtTest - FindSqRt]==] ClampTo SoftClamp [==[StringBuilder - basic]==] [==[StringBuilder - binary]==] [==[StringBuilder - text]==] [==[StringConsumer - basic]==] [==[StringConsumer - binary8]==] [==[StringConsumer - binary16]==] [==[StringConsumer - binary32]==] [==[StringConsumer - binary64]==] [==[StringConsumer - utf8]==] [==[StringConsumer - conditions]==] [==[StringConsumer - ascii]==] [==[StringConsumer - parse int]==] [==[StringConsumer - invalid int]==] [==[StringConsumer - most negative]==] InPlaceReplacement [==[StrCompareIgnoreCase - std::string]==] [==[StrCompareIgnoreCase - std::string_view]==] [==[StrEqualsIgnoreCase - std::string]==] [==[StrEqualsIgnoreCase - std::string_view]==] [==[StrStartsWithIgnoreCase - std::string]==] [==[StrStartsWithIgnoreCase - std::string_view]==] [==[StrEndsWithIgnoreCase - std::string]==] [==[StrEndsWithIgnoreCase - std::string_view]==] FormatArrayAsHex ConvertHexToBytes StrTrimInPlace StrTrimView FixSCCEncoded FixSCCEncodedNegative [==[EncodedString::ReplaceParam - positive]==] [==[EncodedString::ReplaceParam - negative]==] Authentication_KeyExchangeOnly Authentication_PAKE Authentication_AuthorizedKey Authentication_Combined [==[Encryption handling]==] [==[Squirrel -> JSON conversion]==] [==[JSON -> Squirrel conversion]==] [==[WindowDesc - ini_key uniqueness]==] [==[WindowDesc - ini_key validity]==] [==[WindowDesc - NWidgetParts properly closed]==] [==[WindowDesc - NWidgetPart validity]==] [==[SpiralTileSequence - minimum]==] [==[SpiralTileSequence - odd]==] [==[SpiralTileSequence - even]==] [==[SpiralTileSequence - zero hole]==] [==[SpiralTileSequence - normal hole]==] [==[Utf8View - empty]==] [==[Utf8View - invalid]==] [==[Utf8View - iterate]==])
